41 blog article card
202306-NEA-DZ-FEW/team-f pull request #58
Opened 2023-10-17 20:17 UTC by SaraBegache

- [ ] Made an Article Card component
- [ ] Added responsivness

2023-10-20 11:56 UTC, darinetag commented on src/components/ArticleCard.js
> +            {imageUrl && <img src={imageUrl} alt={title} className='w-full' />}
Amazing, make sure to use "Image" and import it from "next" instead of using "img" for built-in optimization purposes. 
ps; when writing in git use the imperative form and present simple for eg: 
- **add** responsiveness 
...

2023-10-20 11:58 UTC, darinetag requested changes
Amazing, make sure to use "Image" and import it from "next" instead of using "img" for built-in optimization purposes.
ps; when writing in git use the imperative form and present simple for eg:

add responsiveness
...

2023-10-21 11:27 UTC, ismail-benlaredj commented
Hey Sara, it appears there might be some confusion regarding the components this the component the you should work on 
[component link](https://www.figma.com/file/qPnL9lWyzueSXanLXNtkDG/let's-share-(Copy)?type=design&node-id=122-620&mode=design&t=5DeVBuMti9Pxz0rn-4)

2023-10-24 11:39 UTC, ismail-benlaredj approved these changes

2023-10-24 11:40 UTC, merged